# This Dockerfile is symlinked to the blueprint folders except base,
# because most of the time the Dockerfile content will be the same.
FROM ghcr.io/cownetwork/spigot-base:v0.20.1 as builder
COPY . .
RUN ./collect.sh

FROM ghcr.io/cownetwork/spigot-base:v0.20.1
COPY --from=builder /opt/spigot/ .
