on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      s3proxy: # yeah, this is pretty ghetto, but we can save costs, if we don't acutally deploy this.
        image: pottava/s3-proxy
        ports:
          - 80:80
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_API_ENDPOINT: ${{ env.S3_ENDPOINT }}
    steps:
      - uses: actions/checkout@v2
      - name: Add cdn.cow.network to /etc/hosts
        run: sudo echo "127.0.0.1 cdn.cow.network" >> /etc/hosts
      - name: Run build script
        run: ./build.sh
        

